name: Tests

on:
  pull_request:
    branches: [develop, main]

jobs:
  test:
    name: Run extension tests
    strategy:
      matrix:
        package: [ 'extension' ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci && npm i --workspaces
      - name: Run tests for ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: xvfb-run -a npm test
